---
services: docker

env:
  - distro: alpine:3.4
    init: "sh -c 'while true; do sleep 1; done'"
    run_opts: ""

before_install:
  # Pull container.
  - docker pull alpine:3.4
  - docker build -t haterd/node:latest tests/
script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run -it -d --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} haterd/node:latest "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/